{{- if .Values.primary.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}-primary
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
    component: primary
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.primary.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "postgres.primarySelectorLabels" . | nindent 4 }}
{{- end }}
