apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ default .Release.Namespace .Values.gateway.namespace }}
  labels:
    {{- include "istio-gateway.labels" . | nindent 4 }}
spec:
  selector:
    {{- toYaml .Values.gateway.selector | nindent 4 }}
  servers:
    - port:
        number: {{ .Values.gateway.port }}
        name: {{ .Values.gateway.protocol | lower }}
        protocol: {{ .Values.gateway.protocol }}
      hosts:
        {{- range .Values.gateway.hosts }}
        - {{ . | quote }}
        {{- end }}
