{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "paper-catalog.serviceAccountName" . }}
  labels:
    {{- include "paper-catalog.labels" . | nindent 4 }}
{{- end }}
